name: Deploy Website
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install
      - run: npm run build
      - name: Create publish directory
        run: mkdir -p publish/
      - name: Copy build output to publish directory
        run: cp -r dist/* publish/
      - name: Copy repo contents to publish directory
        run: cp -r repo/* publish/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: publish/
      - id: deployment
        if: github.ref_name == 'main'
        uses: actions/deploy-pages@v4
